---
# tasks file for rosonpve

- name: Build configdrive
  include: build_configdrive.yml
  delegate_to: "{{ rosonpve_vm_pve_node }}"

- name: Deploy VM
  include: vmcreate.yml
  delegate_to: "{{ rosonpve_vm_pve_node }}"

- name: Wait for deployment to be finished
  wait_for_connection:
    delay: 10
    timeout: 1200
