---
# tasks file for rosonpve

- name: Build configdrive
  include: build_configdrive.yml
  delegate_to: "{{ rosonpve_vm_pve_node }}"

- name: Deploy VM
  include: vmcreate.yml
  with_items: "{{ play_hosts }}"
  when: "hostvars[item].inventory_hostname == inventory_hostname"
  delegate_to: "{{ rosonpve_vm_pve_node }}"

- name: Wait for deployment to be finished
  remote_user: rancher
  wait_for_connection:
    delay: 10
    timeout: 120
